package com.example.SmartParkingLot.service;

import com.example.SmartParkingLot.dto.ParkingSpotRequest;
import com.example.SmartParkingLot.entity.ParkingSpot;
import com.example.SmartParkingLot.entity.SpotType;
import com.example.SmartParkingLot.exception.ResourceNotFoundException;
import com.example.SmartParkingLot.repository.ParkingSpotRepository;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;

@Service
public class ParkingSpotService {

    private final ParkingSpotRepository spotRepo;

    public ParkingSpotService(ParkingSpotRepository spotRepo) {
        this.spotRepo = spotRepo;
    }

    // Create single spot
    public ParkingSpot createSpot(ParkingSpotRequest req) {
        ParkingSpot spot = new ParkingSpot();
        // if your entity has spotNumber, you'll want to set it. For now keep default/autogenerated.
        spot.setSpotType(req.getSpotType());
        spot.setOccupied(req.getOccupied() != null && req.getOccupied());
        return spotRepo.save(spot);
    }

    // Bulk create n spots of a given type
    public List<ParkingSpot> createBulkSpots(SpotType type, int count) {
        if (count <= 0) throw new IllegalArgumentException("count must be > 0");
        List<ParkingSpot> list = new ArrayList<>(count);
        for (int i = 0; i < count; i++) {
            ParkingSpot p = new ParkingSpot();
            p.setSpotType(type);
            p.setOccupied(false);
            list.add(p);
        }
        return spotRepo.saveAll(list);
    }

    // Update spot (type or occupied)
    public ParkingSpot updateSpot(Long id, ParkingSpotRequest req) {
        ParkingSpot spot = spotRepo.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Spot not found: " + id));

        if (req.getSpotType() != null) spot.setSpotType(req.getSpotType());
        if (req.getOccupied() != null) spot.setOccupied(req.getOccupied());

        return spotRepo.save(spot);
    }

    // Delete spot
    public void deleteSpot(Long id) {
        ParkingSpot spot = spotRepo.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Spot not found: " + id));
        spotRepo.delete(spot);
    }

    // Simple fetches
    public List<ParkingSpot> getAllSpots() { return spotRepo.findAll(); }

    public List<ParkingSpot> listAvailableByType(SpotType type) {
        return spotRepo.findBySpotTypeAndOccupied(type, false);
    }
}
